import { modelPolicy } from "./policy"
import type { Settings } from "./schema"

export const BEGIN_MARKER = "# >>> CLIProxyAPIProvider managed begin"
export const END_MARKER = "# >>> CLIProxyAPIProvider managed end"

type BlockSettings = Pick<
  Settings,
  "apiBackend" | "baseUrl" | "defaultModel" | "defaultReasoningEffort" | "envKey" | "webSearch"
>

const LEGACY_BLOCKS = [
  /# >>> CLIProxyAPIProvider managed begin[\s\S]*?# >>> CLIProxyAPIProvider managed end\n?/g,
  /# >>> ocx-models-plugin managed begin[\s\S]*?# >>> ocx-models-plugin managed end\n?/g,
  /# >>> ocx-models-plugin route begin[\s\S]*?# >>> ocx-models-plugin route end\n?/g,
] as const

const STANDARD_TABLES = [
  { name: "endpoints", ownedKeys: ["models_base_url"] },
  { name: "models", ownedKeys: ["default", "web_search", "default_reasoning_effort"] },
  { name: "subagents.models", ownedKeys: ["default", "sisyphus"] },
] as const

type StandardTable = (typeof STANDARD_TABLES)[number]

export function buildManagedBlock(settings: BlockSettings, modelIds: readonly string[]): string {
  const lines = [
    "[endpoints]",
    `models_base_url = ${tomlString(settings.baseUrl)}`,
    "",
    "[models]",
    `default = ${tomlString(settings.defaultModel)}`,
    `web_search = ${tomlString(settings.webSearch)}`,
    `default_reasoning_effort = ${tomlString(settings.defaultReasoningEffort)}`,
    "",
    "[subagents.models]",
    `default = ${tomlString(settings.defaultModel)}`,
    `sisyphus = ${tomlString(settings.defaultModel)}`,
    "",
    BEGIN_MARKER,
    "# Generated by cliproxy-api-provider. Do not edit inside this block.",
    "",
  ]
  const managedModelIds = [
    ...new Set([...modelIds, settings.defaultModel, settings.webSearch]),
  ].sort()
  for (const modelId of managedModelIds) lines.push(...modelLines(settings, modelId))
  lines.push(END_MARKER, "")
  return lines.join("\n")
}

export function transformConfig(current: string, block: string): string {
  let unmanaged = current
  for (const pattern of LEGACY_BLOCKS) unmanaged = unmanaged.replace(pattern, "")
  for (const table of STANDARD_TABLES) {
    unmanaged = mergeStandardTable(unmanaged, table, extractOwnedAssignments(block, table))
  }
  const managedBlock = block.slice(block.indexOf(BEGIN_MARKER)).trim()
  return `${[unmanaged.trim(), managedBlock].filter((part) => part.length > 0).join("\n\n")}\n`
}

function extractOwnedAssignments(content: string, table: StandardTable): readonly string[] {
  const match = tablePattern(table.name).exec(content)
  const body = match?.[2]
  if (body === undefined) return []
  return body.split("\n").filter((line) => isOwnedAssignment(line, table))
}

function mergeStandardTable(
  content: string,
  table: StandardTable,
  desiredAssignments: readonly string[],
): string {
  const matches = [...content.matchAll(tablePattern(table.name))]
  const preservedLines = trimBlankLines(
    matches.flatMap((match) => {
      const body = match[2]
      return body === undefined
        ? []
        : body.split("\n").filter((line) => !isOwnedAssignment(line, table))
    }),
  )
  const firstHeader = matches[0]?.[1] ?? `[${table.name}]`
  const section = `${firstHeader}\n${[...preservedLines, ...desiredAssignments].join("\n")}\n`
  if (matches.length === 0) return appendSection(content, section)
  let occurrence = 0
  return content.replace(tablePattern(table.name), () => {
    occurrence += 1
    return occurrence === 1 ? section : ""
  })
}

function appendSection(content: string, section: string): string {
  const prefix = content.trimEnd()
  return prefix.length === 0 ? section : `${prefix}\n\n${section}`
}

function isOwnedAssignment(line: string, table: StandardTable): boolean {
  const match = line.match(/^\s*(?:"([^"]+)"|'([^']+)'|([A-Za-z0-9_.-]+))\s*=/)
  const key = match?.[1] ?? match?.[2] ?? match?.[3]
  return key !== undefined && table.ownedKeys.some((ownedKey) => ownedKey === key)
}

function tablePattern(name: string): RegExp {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  return new RegExp(
    `^(\\s*\\[${escaped}\\][^\\n]*)(?:\\n|$)([\\s\\S]*?)(?=^\\s*\\[|(?![\\s\\S]))`,
    "gm",
  )
}

function trimBlankLines(lines: readonly string[]): readonly string[] {
  let start = 0
  let end = lines.length
  while (start < end && lines[start]?.trim().length === 0) start += 1
  while (end > start && lines[end - 1]?.trim().length === 0) end -= 1
  return lines.slice(start, end)
}

function modelLines(settings: BlockSettings, modelId: string): readonly string[] {
  const policy = modelPolicy(modelId)
  const lines = [
    `[model.${tomlString(modelId)}]`,
    `model = ${tomlString(modelId)}`,
    `base_url = ${tomlString(settings.baseUrl)}`,
    `name = ${tomlString(`CLIProxy ${modelId}`)}`,
    `env_key = ${tomlString(settings.envKey)}`,
    `api_backend = ${tomlString(settings.apiBackend)}`,
    `context_window = ${policy.contextWindow}`,
    `supports_reasoning_effort = ${policy.reasoning !== null}`,
  ]
  if (policy.supportsBackendSearch) lines.push("supports_backend_search = true")
  if (policy.reasoning !== null) {
    lines.push(`reasoning_effort = ${tomlString(policy.reasoning.defaultEffort)}`)
    lines.push(`reasoning_efforts = [${policy.reasoning.efforts.map(tomlString).join(", ")}]`)
  }
  return [...lines, ""]
}

function tomlString(value: string): string {
  return JSON.stringify(value)
}
